#!/bin/bash
# Get the folder of the real bash script, in case
# we invoked this through symbolic link.
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# Invoke i.py in the same folder
python3 "$SCRIPT_DIR/i.py" "$@"